expl_cfg:
  seq_expl_len: 3  # >0 to enable
  k_expl: 0.05
  norm_loss: false
  use_actor_feat: false
  use_ema_encoder: false
  ema_tau: 1.0  # always use latest encoder
  lr: 1e-4
  embed_dim: 128
  baseline: 'ngu'

  decoder_embed_dim: 64
  decoder_num_heads: 2
  decoder_depth: 1

  use_my_ratio: false # 是否使用自己的方法
  sequencelevel: 0
  attn_selet_way: 0
  ratio_s2aanda2s: 0.5
  attn_ratio_weight: 1.0

  expl_seq_len_ratio: 1  # >=2 to enable
  # anneal_k_ratio: False # 是否动态调整权重比例，随着运行步数的增加逐步变小
  norm_loss_ratio: false
  use_cls_ratio: true
  bert_lr_ratio: 1e-4
  decoder_num_heads_ratio: 2
  decoder_depth_ratio: 1